options:
    merge-default-rules: true
files:
    include:
        - resources/assets/sass/**/*.scss
    ignore:
        - resources/assets/sass/_vendor/**/*.scss

rules:
    attribute-quotes: 0
    border-zero: 0
    brace-style:
        - 1
        - style: stroustrup
    class-name-format: 0
    declarations-before-nesting: 0
    empty-line-between-blocks: 1
    final-newline: 0
    force-attribute-nesting: 0
    force-element-nesting: 0
    force-pseudo-nesting: 0
    indentation:
        - 1
        - size: 4
    leading-zero: 0
    mixins-before-declarations: 0
    nesting-depth:
        - 1
        - max-depth: 4
    no-css-comments: 0
    no-color-literals:
        - 1
        - allow-rgba: true
    no-invalid-hex: 2
    no-misspelled-properties: 2
    no-qualifying-elements: 0
    no-transition-all: 0
    no-url-domains: 0
    no-url-protocols: 0
    no-vendor-prefixes:
        - 1
        - ignore-non-standard: true
    quotes: 0
    shorthand-values: 0
    single-line-per-selector: 0
    variable-name-format: 0
    url-quotes: 0
    placehoder-in-extend: 0
